Remove null from examples
This causes Swagger UI to fail to load with the following error:

    TypeError: Swagger 2.0 does not support null types ([object Object]).
    See https://github.com/swagger-api/swagger-spec/issues/229.

Signed-off-by: Kevin Locke <kevin@kevinlocke.name>